const RESULTS_MAP = {
  'blep': {
    title: 'Excellent juge de caractère',
contents: "Votre extérieur dérisoire dément le vilain limier à l'intérieur, et vous avez un nez puissant, à la fois pour flairer les désirs des gens et pour trouver de la nourriture délicieuse. Vous riez quand vous êtes confus et inclinez la tête lorsque les choses sont drôles. Dans les œuvres de fiction, vos personnages préférés sont ceux qui ont des histoires complexes, et vous aimez les sous-intrigues sinueuses. Cependant, vous aimez les phrases courtes. Vous avez toujours voulu créer un jardin. Malheureusement, les plantes ne sont pas aussi faciles à comprendre que les humains, et la dernière fois que vous a pris soin d'une fleur, ça ne s'est pas très bien passé. Cependant, vous prenez très bien soin de vos amis, et ils ont de la chance de vous avoir. ",  },
  'burger': {
    title: 'Fort et déterminé',
contents: "Dans cette image, vous êtes en train de ronger un jouet en tissu, et il faudrait une centaine de tir à la corde pour l'arracher à votre morsure. De même, vous êtes plus susceptible d'influencer les gens autour de vous que d'être influencé par La qualité de votre travail est très importante pour vous. Vous êtes un penseur visuel et vous êtes bon pour trouver des analogies entre deux sujets disparates. Vous aimez aussi partager des blagues et des mèmes avec vos amis. Vous êtes pointilleux sur ce que vous mangez, mais vous pourrez également essayer chaque nouveau plat une fois. Vous pensez que la contradiction est le début de votre âme. Parfois, vous ne vous en rendez pas compte, mais beaucoup de gens vous admirent. ",  },
  'cart': {
    title: 'Perfectionniste avec un côté gentil',
contents: "Vous êtes chaleureux et bon pour améliorer la journée de quiconque. Secrètement, vous aimez l'idée d'être un rebelle, mais la plupart des rebelles continuent dans votre tête. Vous aimez créer des organigrammes. Vous êtes pressé de finir tout ce que vous avez à faire pour la journée et lorsque vous êtes concentré, il faut beaucoup pour briser votre concentration. Votre couleur préférée a changé plusieurs fois au cours de votre vie. Il est important pour vous d'avoir des débouchés créatifs et une indépendance personnelle. Même si la plupart des valeurs de la société ne font pas trop d'efforts, vous appréciez vraiment les gens qui font de gros efforts. Vous êtes très motivé, ce qui inspire souvent les autres. ",  },
  'dopey': {
    title: 'Calme avec un côté réfléchissant',
contents: "Vous aimez la randonnée, la course à pied, le sprint, la marche, le jogging, la marche et les monocycles. Je plaisante! Les monocycles ne sont pas pour les chiens! Votre nom d'utilisateur AIM était. Vous ajoutez parfois un visage souriant à côté de la signature de votre carte de crédit. Parfois, vous dites aux gens vous portez secrètement une chaîne en or avec une breloque de gants de boxe et une étiquette de chien avec le nom de Rocky. Cependant, lorsque vous êtes seul, vous méditez sur la commercialisation croissante de la capacité créative humaine et aimez réciter Marx tout en marchant dans le Votre mot de passe Club Penguin est la représentation hexadécimale du caractère chinois pour la force. ",  },
  'happy': {
    title: 'Force postitive du monde',
contents: "Vous êtes optimiste et confiant dans votre capacité à changer quelque chose pour le mieux, que ce soit un groupe, un processus ou vous-même. Il est difficile de vous étiqueter comme introverti ou extraverti. Vous avez beaucoup de livres que vous ont eu l'intention de lire, et la semaine prochaine, vous en commencerez un. Lorsque vous vous réveillez le matin, il est difficile pour vous de vous souvenir de ce dont vous avez rêvé. Vous aimez le bruit de la pluie mais n'aimez pas vous mouiller. Vous êtes plus courageux que la personne moyenne, en particulier en termes de partage de qui vous êtes. En même temps, vous avez tendance à être très conscient de la façon dont vos actions affectent les autres. Vous craignez de ne pas en faire assez, mais pour tout le monde, vous êtes! ",  },
  'nerd': {
    title: 'Ouvert d-esprit et avec un grand coeur',
contents: "Vous êtes le chiot Harry Potter. Le chiot choisi pour redresser les torts dans le monde et ramener l'harmonie sur la Terre du Milieu. Vous appréciez le poulet fermier, la lecture des biographies historiques et la reprise du test de personnalité Myers Briggs pour réaffirmer que votre personnalité le type est aussi rare qu'un flocon de neige atterrissant sur le dos d'un jaguar. Vous avez des pouvoirs magiques, mais je recommanderais fortement de ne pas mettre cela sur votre CV, car (1) les gens pourraient ne pas être d'accord et (2) vous êtes un chien et cherchez un emploi traditionnel pourrait déjà être difficile. "  },
  'shy': {
    title: 'Parfois timide, mais secrètement aventureux',
    contents: "You are a very thoughtful person, both when it comes to thinking of others and thinking about ideas. You enjoy nature, particularly the way light filters through leaves. In a group, you are almost never the first person to talk, but when you do, people always want you to keep talking. You value the future over the past. You dislike puns and enjoy handwritten notes; handwritten puns are acceptable. It is important to you to try something new each week. Though you are afraid of heights, you sometimes google pictures of tall cliffs just to scare yourself a little. You're not afraid to take on a challenge, and that is very cool.",
  },
  'sleeping': {
    title: 'Indépendant et libre',
contents: "Vous êtes très excité par les nombreuses choses que vous trouvez importantes, et cette image a été volée pendant un bref moment de détente. La capacité à prendre des risques est importante pour vous, et vous vous agitez lorsque vous sentez que vous n'avez pas changé dans un certain temps. Vous êtes bon à articuler vos idées. Les horloges sont l'une de vos choses les moins préférées. Vous êtes toujours séparé de votre groupe lorsque vous explorez un nouvel endroit, alors Dieu merci, vous avez un excellent sens de l'orientation. La réponse à votre sécurité La question est toujours le numéro de votre carte de bibliothèque. Vous avez un talent caché que peu de gens connaissent, mais comme j'ai déjà donné votre question de sécurité, je garderai cela secret. ",  },
  'sleepy': {
    title: 'Plus fort que ce que vous pensez.',
contents: "Vous appelez cela de la méditation, mais cela ressemble plus à fermer les yeux entre les répétitions. Vous l'appelez lever des poids, mais c'est plutôt une bonne excuse pour boire du Gatorade. Vous vous décrivez comme du type C - C pour se détendre. Votre les plaisanteries sont souvent bien synchronisées et appréciées de tous. Vous transcendez les difficultés de la vie, en les parcourant en douceur. Vous mangez des biscuits de fortune, mais ne regardez jamais la fortune en raison de votre profonde confiance interne. La sieste est une compétence que vous pratiquez souvent, mais l'homme oh mec, une fois que votre moteur interne démarre, vous vous concentrez à 100%. Peut-être même à 110%. C'est comme beaucoup de mise au point. Tant de mise au point. Des seaux de mise au point. Toute une Ford Focus. Mais en ce moment, vous êtes en train de somnoler et c'est cool . Vous allez résoudre P = NP un peu plus tard. ",  }
};
